#!/bin/python3

import math
import os
import random
import re
import sys


def equalStacks(h1, h2, h3):
  sum1=sum(h1)
  sum2=sum(h2)
  sum3=sum(h3)
  
  while(sum1!=sum2 or sum1!=sum3 or sum2!=sum1 or sum2!=sum3 or sum3!=sum1 or sum3!=sum2):
    i=max(sum1,sum2,sum3)
    print(i)
    if(i==sum1):
      h1.pop(0)
      sum1=sum(h1)
      print("sum1 is",sum1)
    elif(i==sum2):
      h2.pop(0)
      sum2=sum(h2)
      print("sum2 is",sum2)
    elif(i==sum3):
      h3.pop(0)
      sum3=sum(h3)
      print("sum3 is",sum3)
  return sum1
    
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n1 = int(first_multiple_input[0])

    n2 = int(first_multiple_input[1])

    n3 = int(first_multiple_input[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
