#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'rotateLeft' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER d
#  2. INTEGER_ARRAY arr
#

def rotateLeft(d, arr,n):

  temp=arr[0]
  for i in range(0,d):
    for j in range(0,n-1):
      arr[j]=arr[j+1]
    arr[n-1]=temp
    temp=arr[0]
  
  for x in arr:
    print(x, end=' ')

if __name__ == '__main__':
   n, d = map(int, input().split())
   arr = [int(x) for x in input().split()]
   rotateLeft(d,arr,n)
