#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
  arr.sort()
  max=0
  min=0
  for i in range(1,5):
    max=max+arr[i]
  for i in range(0,4):
    min=min+arr[i]
  print("{} {}".format(min,max))
    # Write your code here

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
