#!/bin/python3

import math
import os
import random
import re
import sys


def minimumNumber(n, password):
  num=l=u=s=0
  numbers = "0123456789"
  lower_case = "abcdefghijklmnopqrstuvwxyz"
  upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  special_characters = "!@#$%^&*()-+"
  for i in password:
    if i in numbers:
      num+=1
    if i in lower_case:
      l+=1
    if i in upper_case:
      u+=1
    if i in special_characters:
      s+=1
  list1=[num,l,u,s]
  if(0 not in list1):
      if(n>6):
        return 0
      else:
        return 6-n
    
  else:
    c=list1.count(0)
    if(n+c>=6):
      return c
    else:
      return 6-(n+c)+c
        
    # Return the minimum number of characters to make the password strong

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
